// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MiGuachincheWeb.Models
{
    public partial class PlatoRestaurante
    {
        public int id { get; set; }
        public int plato_Id { get; set; }
        public int restaurante_Id { get; set; }


        [Range(1,5,ErrorMessage ="La valoracion ha de ir de 1 a 5")]
        public int valoracion { get; set; }
        public bool activo { get; set; }

        public virtual Plato plato { get; set; }
        public virtual Restaurante restaurante { get; set; }
        public virtual ICollection<CustomUser> listaUsers { get; set; }

        public PlatoRestaurante()
        {
            this.listaUsers = new HashSet<CustomUser>();
        }
    }
}