// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiGuachincheWeb.Models
{
    public partial class PlatoRestaurante
    {
        public int id { get; set; }
        public int plato_Id { get; set; }
        public int restaurante_Id { get; set; }
        public int? valoracion { get; set; }
        public bool activo { get; set; }

        public virtual Plato plato { get; set; }
        public virtual Restaurante restaurante { get; set; }
        public virtual ICollection<CustomUser> listaUsers { get; set; }

        public PlatoRestaurante()
        {
            this.listaUsers = new HashSet<CustomUser>();
        }
    }
}