// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MiGuachincheWeb.Models
{
    public partial class Restaurante
    {
        public int RestauranteId { get; set; }

        [Required(ErrorMessage = "El campo 'Nombre' es requerido")]
        public string Nombre { get; set; }
        public string Rest_Url { get; set; }

        [Required(ErrorMessage = "El campo 'Teléfono' es requerido")]
        [StringLength(9, ErrorMessage = "El campo 'Teléfono' debe contener 9 números")]
        [DisplayName("Teléfono")]
        public string telefono { get; set; }

        [DisplayName("Valoración")]
        [Required(ErrorMessage = "El campo 'Valoración' es requerido")]
        [Range(0, 5, ErrorMessage = "El campo 'Valoración' no puede ser menor que 0, y mayor que 5")]
        public int? valoracion { get; set; }
        public int Id_tipo { get; set; }
        public int zonaId { get; set; }

        [DisplayName("Descripción")]
        [Required(ErrorMessage = "El campo 'Descripción' es requerido")]
        public string Descripcion { get; set; }

        [DisplayName("Especialidad")]
        public virtual TipoRestaurante Id_tipoNavigation { get; set; }
        public virtual Zona zona { get; set; }
        public virtual ICollection<Plato> platos { get; set; }
        public virtual ICollection<CustomUser> usuarios { get; set; }

        public virtual ICollection<Reserva> reservas { get; set; }

    }
}