// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiGuachincheWeb.Models
{
    public partial class Restaurante
    {
        public int RestauranteId { get; set; }
        public string Nombre { get; set; }
        public string Rest_Url { get; set; }
        public string telefono { get; set; }
        public int? valoracion { get; set; }
        public int Id_tipo { get; set; }
        public int zonaId { get; set; }

        public virtual TipoRestaurante Id_tipoNavigation { get; set; }
        public virtual Zona zona { get; set; }
        public virtual ICollection<Plato> platos { get; set; }
        public virtual ICollection<CustomUser> usuarios { get; set; }

        public virtual ICollection<Reserva> reservas { get; set; }

    }
}