// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiGuachincheWeb.Models
{
    public partial class tipoRestaurante
    {
        public tipoRestaurante()
        {
            restaurantes = new HashSet<restaurante>();
        }

        public int id { get; set; }
        public string nombre { get; set; }

        public virtual ICollection<restaurante> restaurantes { get; set; }
    }
}