// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiGuachincheWeb.Models
{
    public partial class tipo
    {
        public tipo()
        {
            platos = new HashSet<plato>();
        }

        public int id { get; set; }
        public string nombre { get; set; }

        public virtual ICollection<plato> platos { get; set; }
    }
}