// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiGuachincheWeb.Models
{
    public partial class Tipo
    {
        public int id { get; set; }
        public string nombre { get; set; }

        public virtual ICollection<Plato> platos { get; set; }

        public Tipo()
        {
            platos = new HashSet<Plato>();
        }
    }
}