// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiGuachincheWeb.Models
{
    public partial class user_restaurante
    {
        public int id { get; set; }
        public string usuario_Id { get; set; }
        public int restaurante_Id { get; set; }

        public virtual restaurante restaurante { get; set; }

        public virtual CustomUser customUser { get; set; }

        public virtual ICollection<user_restaurante> userRestaurante { get; set; }


        public user_restaurante()
        {
            this.userRestaurante = new HashSet<user_restaurante>();
        }
    }
}