// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiGuachincheWeb.Models
{
    public partial class UserPlatoRestaurante
    {
        public int id { get; set; }
        public string usuario_Id { get; set; }
        public int plato_restaurante_Id { get; set; }

        public virtual PlatoRestaurante plato_restaurante { get; set; }

        public virtual CustomUser custom_user { get; set; }
    }
}