// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MiGuachincheWeb.Models
{
    public partial class Zona
    {
        public Zona()
        {
            restaurantes = new HashSet<Restaurante>();
        }

        public int Zona_id { get; set; }
        [DisplayName("Nombre")]
        [Required(ErrorMessage = "El campo 'Nombre' es requerido")]
        public string nombre { get; set; }
        [DisplayName("Descripción")]
        [Required(ErrorMessage = "El campo 'Descripción' es requerido")]
        public string descripcion { get; set; }

        public string ImagenURL { get; set; }

        public virtual ICollection<Restaurante> restaurantes { get; set; }
    }
}